# UC-01 — Cadastro de Cliente

```mermaid
sequenceDiagram
    actor Cliente
    participant Sistema
    participant EmailService as "Serviço de Email"

    Cliente->>Sistema: inserirEmail()

    Sistema->>EmailService: enviarCodigoConfirmacao(email)
    EmailService-->>Cliente: receberCodigo()

    Cliente->>Sistema: confirmarCodigo(codigo)

    alt Código válido
        Sistema-->>Cliente: solicitarDadosPessoais()

        Cliente->>Sistema: enviarDados(nome, cpf, etc)

        Sistema->>Sistema: verificarDadosValidos()

        alt Dados válidos e únicos
            Sistema-->>Cliente: cadastroConfirmado()
        else Email ou CPF já existente
            Sistema-->>Cliente: informarContaExistente()
        end

    else Código inválido
        Sistema-->>Cliente: erroCodigo()
    end
